import { unstable_setRequestLocale } from "next-intl/server";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: "en" | "ru" };
}) {
  unstable_setRequestLocale(locale);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
